/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Auto-generated by `supabase generate-types` (via Supabase MCP) against
// project oyinjdprggupasmtkzoh. Regenerate after any schema/RPC change
// instead of hand-editing: types must stay in sync with the live database.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      caregiver_profiles: {
        Row: {
          created_at: string | null
          email: string | null
          id: string
          phone: string | null
          profile_id: string
          relationship: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          email?: string | null
          id?: string
          phone?: string | null
          profile_id: string
          relationship: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          email?: string | null
          id?: string
          phone?: string | null
          profile_id?: string
          relationship?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "caregiver_profiles_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_plans: {
        Row: {
          attention_minutes: number | null
          completed: boolean | null
          created_at: string | null
          date: string
          elderly_profile_id: string
          id: string
          logic_minutes: number | null
          memory_minutes: number | null
          orientation_minutes: number | null
        }
        Insert: {
          attention_minutes?: number | null
          completed?: boolean | null
          created_at?: string | null
          date: string
          elderly_profile_id: string
          id?: string
          logic_minutes?: number | null
          memory_minutes?: number | null
          orientation_minutes?: number | null
        }
        Update: {
          attention_minutes?: number | null
          completed?: boolean | null
          created_at?: string | null
          date?: string
          elderly_profile_id?: string
          id?: string
          logic_minutes?: number | null
          memory_minutes?: number | null
          orientation_minutes?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "daily_plans_elderly_profile_id_fkey"
            columns: ["elderly_profile_id"]
            isOneToOne: false
            referencedRelation: "elderly_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_tasks: {
        Row: {
          completed: boolean | null
          completed_at: string | null
          daily_plan_id: string
          id: string
          title: string
          type: string
        }
        Insert: {
          completed?: boolean | null
          completed_at?: string | null
          daily_plan_id: string
          id?: string
          title: string
          type: string
        }
        Update: {
          completed?: boolean | null
          completed_at?: string | null
          daily_plan_id?: string
          id?: string
          title?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "daily_tasks_daily_plan_id_fkey"
            columns: ["daily_plan_id"]
            isOneToOne: false
            referencedRelation: "daily_plans"
            referencedColumns: ["id"]
          },
        ]
      }
      elderly_profiles: {
        Row: {
          created_at: string | null
          date_of_birth: string | null
          high_contrast_enabled: boolean | null
          id: string
          large_text_enabled: boolean | null
          preferred_language: string | null
          profile_id: string
          sound_enabled: boolean | null
          updated_at: string | null
          vibration_enabled: boolean | null
        }
        Insert: {
          created_at?: string | null
          date_of_birth?: string | null
          high_contrast_enabled?: boolean | null
          id?: string
          large_text_enabled?: boolean | null
          preferred_language?: string | null
          profile_id: string
          sound_enabled?: boolean | null
          updated_at?: string | null
          vibration_enabled?: boolean | null
        }
        Update: {
          created_at?: string | null
          date_of_birth?: string | null
          high_contrast_enabled?: boolean | null
          id?: string
          large_text_enabled?: boolean | null
          preferred_language?: string | null
          profile_id?: string
          sound_enabled?: boolean | null
          updated_at?: string | null
          vibration_enabled?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "elderly_profiles_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      emergency_events: {
        Row: {
          acknowledged_at: string | null
          acknowledged_by: string | null
          cancelled_at: string | null
          confirmed_at: string | null
          elderly_profile_id: string
          id: string
          metadata: Json | null
          notified_at: string | null
          resolved_at: string | null
          severity: string | null
          status: string
          triggered_at: string | null
          type: string
        }
        Insert: {
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          cancelled_at?: string | null
          confirmed_at?: string | null
          elderly_profile_id: string
          id?: string
          metadata?: Json | null
          notified_at?: string | null
          resolved_at?: string | null
          severity?: string | null
          status?: string
          triggered_at?: string | null
          type: string
        }
        Update: {
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          cancelled_at?: string | null
          confirmed_at?: string | null
          elderly_profile_id?: string
          id?: string
          metadata?: Json | null
          notified_at?: string | null
          resolved_at?: string | null
          severity?: string | null
          status?: string
          triggered_at?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "emergency_events_elderly_profile_id_fkey"
            columns: ["elderly_profile_id"]
            isOneToOne: false
            referencedRelation: "elderly_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      emergency_settings: {
        Row: {
          created_at: string | null
          demo_mode: boolean | null
          elderly_profile_id: string
          enabled: boolean | null
          id: string
          notify_caregivers: boolean | null
          response_timeout_seconds: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          demo_mode?: boolean | null
          elderly_profile_id: string
          enabled?: boolean | null
          id?: string
          notify_caregivers?: boolean | null
          response_timeout_seconds?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          demo_mode?: boolean | null
          elderly_profile_id?: string
          enabled?: boolean | null
          id?: string
          notify_caregivers?: boolean | null
          response_timeout_seconds?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "emergency_settings_elderly_profile_id_fkey"
            columns: ["elderly_profile_id"]
            isOneToOne: false
            referencedRelation: "elderly_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      family_links: {
        Row: {
          accepted_at: string | null
          caregiver_profile_id: string | null
          created_at: string | null
          elderly_profile_id: string
          id: string
          invite_code: string | null
          status: string
        }
        Insert: {
          accepted_at?: string | null
          caregiver_profile_id?: string | null
          created_at?: string | null
          elderly_profile_id: string
          id?: string
          invite_code?: string | null
          status?: string
        }
        Update: {
          accepted_at?: string | null
          caregiver_profile_id?: string | null
          created_at?: string | null
          elderly_profile_id?: string
          id?: string
          invite_code?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "family_links_caregiver_profile_id_fkey"
            columns: ["caregiver_profile_id"]
            isOneToOne: false
            referencedRelation: "caregiver_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "family_links_elderly_profile_id_fkey"
            columns: ["elderly_profile_id"]
            isOneToOne: false
            referencedRelation: "elderly_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      game_results: {
        Row: {
          attempts: number
          category: string
          completed_at: string | null
          difficulty: string
          duration_seconds: number
          elderly_profile_id: string
          game_type: string
          id: string
          pairs_found: number
          pairs_total: number
          score: number
          sound_enabled: boolean
        }
        Insert: {
          attempts: number
          category: string
          completed_at?: string | null
          difficulty: string
          duration_seconds: number
          elderly_profile_id: string
          game_type?: string
          id?: string
          pairs_found: number
          pairs_total: number
          score?: number
          sound_enabled?: boolean
        }
        Update: {
          attempts?: number
          category?: string
          completed_at?: string | null
          difficulty?: string
          duration_seconds?: number
          elderly_profile_id?: string
          game_type?: string
          id?: string
          pairs_found?: number
          pairs_total?: number
          score?: number
          sound_enabled?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "game_results_elderly_profile_id_fkey"
            columns: ["elderly_profile_id"]
            isOneToOne: false
            referencedRelation: "elderly_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      intake_logs: {
        Row: {
          alert_event_id: string | null
          confirmed_at: string | null
          created_at: string | null
          dose_key: string
          elderly_profile_id: string
          id: string
          medication_id: string
          medication_name: string
          response_time_seconds: number | null
          scheduled_for: string
          severity: string | null
          snooze_count: number
          status: string
          updated_at: string | null
          warning_at: string | null
        }
        Insert: {
          alert_event_id?: string | null
          confirmed_at?: string | null
          created_at?: string | null
          dose_key: string
          elderly_profile_id: string
          id?: string
          medication_id: string
          medication_name: string
          response_time_seconds?: number | null
          scheduled_for: string
          severity?: string | null
          snooze_count?: number
          status?: string
          updated_at?: string | null
          warning_at?: string | null
        }
        Update: {
          alert_event_id?: string | null
          confirmed_at?: string | null
          created_at?: string | null
          dose_key?: string
          elderly_profile_id?: string
          id?: string
          medication_id?: string
          medication_name?: string
          response_time_seconds?: number | null
          scheduled_for?: string
          severity?: string | null
          snooze_count?: number
          status?: string
          updated_at?: string | null
          warning_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "intake_logs_alert_event_id_fkey"
            columns: ["alert_event_id"]
            isOneToOne: false
            referencedRelation: "emergency_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "intake_logs_elderly_profile_id_fkey"
            columns: ["elderly_profile_id"]
            isOneToOne: false
            referencedRelation: "elderly_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      medication_intakes: {
        Row: {
          confirmed_at: string | null
          created_at: string | null
          id: string
          medication_id: string
          response_time_seconds: number | null
          scheduled_for: string
          status: string
        }
        Insert: {
          confirmed_at?: string | null
          created_at?: string | null
          id?: string
          medication_id: string
          response_time_seconds?: number | null
          scheduled_for: string
          status?: string
        }
        Update: {
          confirmed_at?: string | null
          created_at?: string | null
          id?: string
          medication_id?: string
          response_time_seconds?: number | null
          scheduled_for?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "medication_intakes_medication_id_fkey"
            columns: ["medication_id"]
            isOneToOne: false
            referencedRelation: "medications"
            referencedColumns: ["id"]
          },
        ]
      }
      medication_schedules: {
        Row: {
          created_at: string | null
          days_of_week: number[] | null
          enabled: boolean | null
          grace_period_seconds: number | null
          id: string
          medication_id: string
          time: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          days_of_week?: number[] | null
          enabled?: boolean | null
          grace_period_seconds?: number | null
          id?: string
          medication_id: string
          time: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          days_of_week?: number[] | null
          enabled?: boolean | null
          grace_period_seconds?: number | null
          id?: string
          medication_id?: string
          time?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "medication_schedules_medication_id_fkey"
            columns: ["medication_id"]
            isOneToOne: false
            referencedRelation: "medications"
            referencedColumns: ["id"]
          },
        ]
      }
      medications: {
        Row: {
          active: boolean | null
          color: string | null
          created_at: string | null
          dosage: string
          elderly_profile_id: string
          icon: string | null
          id: string
          instructions: string | null
          name: string
          unit: string | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          color?: string | null
          created_at?: string | null
          dosage: string
          elderly_profile_id: string
          icon?: string | null
          id?: string
          instructions?: string | null
          name: string
          unit?: string | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          color?: string | null
          created_at?: string | null
          dosage?: string
          elderly_profile_id?: string
          icon?: string | null
          id?: string
          instructions?: string | null
          name?: string
          unit?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "medications_elderly_profile_id_fkey"
            columns: ["elderly_profile_id"]
            isOneToOne: false
            referencedRelation: "elderly_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      memory_results: {
        Row: {
          correct_answers: number
          created_at: string | null
          exercise_type: string
          id: string
          metadata: Json | null
          score: number
          session_id: string
          total_answers: number
        }
        Insert: {
          correct_answers: number
          created_at?: string | null
          exercise_type: string
          id?: string
          metadata?: Json | null
          score: number
          session_id: string
          total_answers: number
        }
        Update: {
          correct_answers?: number
          created_at?: string | null
          exercise_type?: string
          id?: string
          metadata?: Json | null
          score?: number
          session_id?: string
          total_answers?: number
        }
        Relationships: [
          {
            foreignKeyName: "memory_results_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "memory_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      memory_sessions: {
        Row: {
          category: string
          completed_at: string | null
          difficulty: string | null
          duration_seconds: number
          elderly_profile_id: string
          id: string
          score: number
        }
        Insert: {
          category: string
          completed_at?: string | null
          difficulty?: string | null
          duration_seconds: number
          elderly_profile_id: string
          id?: string
          score: number
        }
        Update: {
          category?: string
          completed_at?: string | null
          difficulty?: string | null
          duration_seconds?: number
          elderly_profile_id?: string
          id?: string
          score?: number
        }
        Relationships: [
          {
            foreignKeyName: "memory_sessions_elderly_profile_id_fkey"
            columns: ["elderly_profile_id"]
            isOneToOne: false
            referencedRelation: "elderly_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          display_name: string
          face_verification_enabled: boolean | null
          id: string
          role: string
          updated_at: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          display_name: string
          face_verification_enabled?: boolean | null
          id: string
          role: string
          updated_at?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          display_name?: string
          face_verification_enabled?: boolean | null
          id?: string
          role?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string | null
          device_id: string
          endpoint: string
          id: string
          last_seen_at: string | null
          p256dh: string
          profile_id: string
          updated_at: string | null
          user_agent: string | null
        }
        Insert: {
          auth: string
          created_at?: string | null
          device_id: string
          endpoint: string
          id?: string
          last_seen_at?: string | null
          p256dh: string
          profile_id: string
          updated_at?: string | null
          user_agent?: string | null
        }
        Update: {
          auth?: string
          created_at?: string | null
          device_id?: string
          endpoint?: string
          id?: string
          last_seen_at?: string | null
          p256dh?: string
          profile_id?: string
          updated_at?: string | null
          user_agent?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      schedules: {
        Row: {
          category: string
          completed: boolean | null
          description: string | null
          elderly_profile_id: string
          id: string
          scheduled_at: string
          title: string
        }
        Insert: {
          category: string
          completed?: boolean | null
          description?: string | null
          elderly_profile_id: string
          id?: string
          scheduled_at: string
          title: string
        }
        Update: {
          category?: string
          completed?: boolean | null
          description?: string | null
          elderly_profile_id?: string
          id?: string
          scheduled_at?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "schedules_elderly_profile_id_fkey"
            columns: ["elderly_profile_id"]
            isOneToOne: false
            referencedRelation: "elderly_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      voice_profiles: {
        Row: {
          audio_url: string
          created_at: string | null
          elderly_profile_id: string
          id: string
          name: string
          type: string
        }
        Insert: {
          audio_url: string
          created_at?: string | null
          elderly_profile_id: string
          id?: string
          name: string
          type: string
        }
        Update: {
          audio_url?: string
          created_at?: string | null
          elderly_profile_id?: string
          id?: string
          name?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "voice_profiles_elderly_profile_id_fkey"
            columns: ["elderly_profile_id"]
            isOneToOne: false
            referencedRelation: "elderly_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_family_invite: {
        Args: { p_invite_code: string }
        Returns: {
          elder_display_name: string
        }[]
      }
      acknowledge_alert: {
        Args: { p_event_id: string }
        Returns: Database['public']['Tables']['emergency_events']['Row']
      }
      cancel_alert: {
        Args: { p_event_id: string }
        Returns: Database['public']['Tables']['emergency_events']['Row']
      }
      confirm_alert: {
        Args: { p_event_id: string }
        Returns: Database['public']['Tables']['emergency_events']['Row']
      }
      create_alert: {
        Args: { p_metadata?: Json; p_type: string }
        Returns: Database['public']['Tables']['emergency_events']['Row']
      }
      create_medication_alert: {
        Args: { p_metadata?: Json; p_severity: string }
        Returns: Database['public']['Tables']['emergency_events']['Row']
      }
      is_linked_caregiver: { Args: { elder_id: string }; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
